In [11]:
#20.09.24

import pandas as pd
import numpy as np

### 0.1 Erstellen Sie das Jupyter-Notebook (JN) 00-WarmingUp und laden Sie das referenzierte Movie-Dataset1. Über welche Dimensionalität verfügt das Movie-Dataset bzw. das erstellte DataFrame?

In [35]:
data = pd.read_csv("movie.csv", encoding="ISO-8859-1") #no UTF-8!
data.shape #dimensions: 4916x28

(4916, 28)

### 0.2 Generieren Sie nachfolgende JN-Ausgabe. Anm.: Die vielen Fragezeichen können ignoriert werden

In [36]:
data

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### 0.3 Selektiert man eine Spalte (z.B. movie_title) des erstellten Movie-DataFrames, ist das Ergebnis vom Typ Series. Treten Sie den Beweis an (<class 'pandas.core.series.Series'>)

In [41]:
selected_data = data.movie_title
print(type(selected_data))

<class 'pandas.core.series.Series'>

### 0.4 Sicherlich wissen Sie noch, dass man DataFrames manipulieren kann. Fügen Sie die Spalte „has_seen“ mit dem Initialwert „0“ hinzu

In [48]:
data["has_seen"] = 0
data.has_seen

0       0
1       0
2       0
3       0
4       0
       ..
4911    0
4912    0
4913    0
4914    0
4915    0
Name: has_seen, Length: 4916, dtype: int64